// react-blockly/src/App.js
import React from 'react';
import 'blockly';
import './blocks/TurtleBlock';
import './App.css';

import BlocklyComponent, { Block } from './components';

class App extends React.Component {
  render() {
    return (
      <div className="App">
        <BlocklyComponent ref={e => this.workspace = e} readOnly={false} grid={{
          spacing: 20,
          length: 3
        }} initialXml={`
          <xml>
            <block type="controls_repeat"></block>
          </xml>
        `}>
          <Block type="controls_repeat" />
          <Block type="moveForward" />
          <Block type="turnRight" />
          <Block type="turnLeft" />
        </BlocklyComponent>
      </div>
    );
  }
}

export default App;

// vue-blockly/src/App.vue
<template>
  <div id="app">
    <blocklyComponent id="blockly" :options="options" ref="blockly">
    </blocklyComponent>
    <p id="code">
      上で組んだブロックのコードが以下に出力されます
      <pre v-html="code"></pre>
    </p>
  </div>
</template>

<script>
import BlocklyComponent from './components/BlocklyComponent.vue'
import './blocks/TurtleBlock';

export default {
  name: 'app',
  components: {
    BlocklyComponent
  },
  data() {
    return {
      code: '',
      options: {
        grid: {
          spacing: 25,
          length: 3,
        },
        toolbox: `
          <xml>
            <block type="controls_repeat"></block>
            <block type="moveForward"></block>
            <block type="turnRight"></block>
            <block type="turnLeft"></block>
          </xml>
        `
      }
    }
  },
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #2c3e50;
}

#blockly {
  position: absolute;
  right: 0;
  top: 0;
  width: 100%;
  height: 50%;
}

#code {
  position: absolute;
  right: 0;
  bottom: 0;
  width: 100%;
  height: 50%;
  margin: 0;
  background-color: beige;
}
</style>
