// vue-blockly/src/components/BlocklyComponent.vue
<template>
  <div>
    <div class="blocklyDiv" ref="blocklyDiv"></div>
    <xml ref="blocklyToolbox" style="display:none"></xml>
  </div>  
</template>

<script>
import Blockly from 'blockly';
import BlocklyJS from 'blockly/javascript';
import * as Ja from 'blockly/msg/ja';
Blockly.setLocale(Ja);

export default {
  name: 'BlocklyComponent',
  props: ['options'],
  data() {
    return {
      workspace: null
    };
  },
  mounted() {
    const options = this.$props.options || {};
    if (!options.toolbox) {
      options.toolbox = this.$refs['blocklyToolbox'];
    }
    this.workspace = Blockly.inject(this.$refs['blocklyDiv'], options);

    const onChangeHandler = (event) => {
      if (event.type == Blockly.Events.MOVE) {
        this.$parent.code = BlocklyJS.workspaceToCode(this.workspace);
      }
    }
    this.workspace.addChangeListener(onChangeHandler);
  }
}
</script>

<style scoped>
.blocklyDiv {
  height: 100%;
  width: 100%;
}
</style>

// react-blockly/src/components/BlocklyComponent.js
import React from 'react';
import Blockly from 'blockly/core';
import BlocklyJS from 'blockly/javascript';
import './BlocklyComponent.css';

import ja from 'blockly/msg/ja';
Blockly.setLocale(ja);

export default class BlocklyComponent extends React.Component {
  onChangeHandler = (event) => {
    if (event.type === Blockly.Events.MOVE) {
      this.props.setCode(BlocklyJS.workspaceToCode(this.workspace));
    }
  }

  componentDidMount() {
    const { initialXml, children, ...rest } = this.props;
    this.workspace = Blockly.inject(
      this.blocklyDiv,
      {
        toolbox: this.toolbox,
        ...rest
      },
    );

    if (initialXml) {
      Blockly.Xml.domToWorkspace(Blockly.Xml.textToDom(initialXml), this.workspace);
    }
    this.workspace.addChangeListener(this.onChangeHandler);
  }

  render() {
    const { children } = this.props;

    return (
      <>
        <div ref={e => this.blocklyDiv = e} id="blocklyDiv" />
        <xml
          xmlns="https://developers.google.com/blockly/xml"
          is="blockly"
          style={{ display: 'none' }}
          ref={(toolbox) => { this.toolbox = toolbox; }}
        >
          {children}
        </xml>
      </>
    )
  }
}
