// angular-blockly/src/app/components/blockly/blockly.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import * as Blockly from 'blockly';
import BlocklyJS from 'blockly/javascript';
import * as Ja from 'blockly/msg/ja';
import '../../blocks/TurtleBlock';

@Component({
  selector: 'app-blockly',
  templateUrl: './blockly.component.html',
  styleUrls: ['./blockly.component.scss']
})

export class BlocklyComponent implements OnInit {
  workspace: any;
  @Output() public code = new EventEmitter();

  onChangeHandler = (event) => {
    if (event.type == Blockly.Events.MOVE) {
      this.code.emit(BlocklyJS.workspaceToCode(this.workspace));
    }
  }

  ngOnInit() {
    const blocklyDiv = document.getElementById('blocklyDiv');

    Blockly.setLocale(Ja);
    this.workspace = Blockly.inject(blocklyDiv, {
      grid: {
        spacing: 20,
        length: 3
      },
      toolbox: `
        <xml>
          <block type="controls_repeat"></block>
          <block type="moveForward"></block>
          <block type="turnRight"></block>
          <block type="turnLeft"></block>
        </xml>
      `
    } as Blockly.BlocklyOptions);
    this.workspace.addChangeListener(this.onChangeHandler);
  }
}

<div id='blocklyDiv'></div>

{{xmlToolBox}}

// vue-blockly/src/components/BlocklyComponent.vue
<template>
  <div>
    <div class="blocklyDiv" ref="blocklyDiv"></div>
    <xml ref="blocklyToolbox" style="display:none"></xml>
  </div>  
</template>

<script>
import Blockly from 'blockly';
import BlocklyJS from 'blockly/javascript';
import * as Ja from 'blockly/msg/ja';
Blockly.setLocale(Ja);

export default {
  name: 'BlocklyComponent',
  props: ['options'],
  data() {
    return {
      workspace: null
    };
  },
  mounted() {
    const options = this.$props.options || {};
    if (!options.toolbox) {
      options.toolbox = this.$refs['blocklyToolbox'];
    }
    this.workspace = Blockly.inject(this.$refs['blocklyDiv'], options);

    const onChangeHandler = (event) => {
      if (event.type == Blockly.Events.MOVE) {
        this.$parent.code = BlocklyJS.workspaceToCode(this.workspace);
      }
    }
    this.workspace.addChangeListener(onChangeHandler);
  }
}
</script>

<style scoped>
.blocklyDiv {
  height: 100%;
  width: 100%;
}
</style>
